# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Email.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Email(object):
    def setupUi(self, Email):
        Email.setObjectName("Email")
        Email.resize(400, 204)
        font = QtGui.QFont()
        font.setPointSize(12)
        Email.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Email)
        self.gridLayout.setObjectName("gridLayout")
        self.email_label = QtWidgets.QLabel(Email)
        self.email_label.setObjectName("email_label")
        self.gridLayout.addWidget(self.email_label, 1, 0, 1, 1)
        self.email_line = QtWidgets.QLineEdit(Email)
        self.email_line.setClearButtonEnabled(True)
        self.email_line.setObjectName("email_line")
        self.gridLayout.addWidget(self.email_line, 1, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(Email)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 2, 0, 1, 1)
        self.password_line = QtWidgets.QLineEdit(Email)
        self.password_line.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setClearButtonEnabled(True)
        self.password_line.setObjectName("passwod_line")
        self.gridLayout.addWidget(self.password_line, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Email)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.authorization_label = QtWidgets.QLabel(Email)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.authorization_label.setFont(font)
        self.authorization_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authorization_label.setObjectName("authorization_label")
        self.gridLayout.addWidget(self.authorization_label, 0, 0, 1, 2)

        self.retranslateUi(Email)
        self.buttonBox.accepted.connect(Email.accept) # type: ignore
        self.buttonBox.rejected.connect(Email.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Email)

    def retranslateUi(self, Email):
        _translate = QtCore.QCoreApplication.translate
        Email.setWindowTitle(_translate("Email", "Авторизация почты"))
        self.email_label.setText(_translate("Email", "Email"))
        self.password_label.setText(_translate("Email", "Password"))
        self.authorization_label.setText(_translate("Email", "Авторизация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Email = QtWidgets.QDialog()
    ui = Ui_Email()
    ui.setupUi(Email)
    Email.show()
    sys.exit(app.exec_())
