# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(450, 200)
        Enter.setMinimumSize(QtCore.QSize(450, 140))
        Enter.setMaximumSize(QtCore.QSize(550, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        Enter.setFont(font)
        Enter.setFocusPolicy(QtCore.Qt.NoFocus)
        Enter.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.centralwidget = QtWidgets.QWidget(Enter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.entry_last_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        self.entry_last_button.setFont(font)
        self.entry_last_button.setAutoDefault(False)
        self.entry_last_button.setFlat(False)
        self.entry_last_button.setObjectName("entry_last_button")
        self.gridLayout.addWidget(self.entry_last_button, 6, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.gridLayout.addWidget(self.email_label, 3, 0, 1, 1)
        self.btn_entry = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_entry.setFont(font)
        self.btn_entry.setFlat(False)
        self.btn_entry.setObjectName("btn_entry")
        self.gridLayout.addWidget(self.btn_entry, 6, 2, 1, 1)
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 4, 0, 1, 1)
        self.password_line = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_line.setFont(font)
        self.password_line.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setClearButtonEnabled(True)
        self.password_line.setObjectName("password_line")
        self.gridLayout.addWidget(self.password_line, 4, 1, 1, 2)
        self.email_line = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_line.setFont(font)
        self.email_line.setClearButtonEnabled(True)
        self.email_line.setObjectName("email_line")
        self.gridLayout.addWidget(self.email_line, 3, 1, 1, 2)
        Enter.setCentralWidget(self.centralwidget)

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Вход"))
        self.entry_last_button.setText(_translate("Enter", "Вход по прошлой сессии"))
        self.label.setText(_translate("Enter", "Введите почту и пароль для авторизации"))
        self.email_label.setText(_translate("Enter", "Email"))
        self.btn_entry.setText(_translate("Enter", "Войти"))
        self.password_label.setText(_translate("Enter", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Enter = QtWidgets.QMainWindow()
    ui = Ui_Enter()
    ui.setupUi(Enter)
    Enter.show()
    sys.exit(app.exec_())
