# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hardware.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Newhard(object):
    def setupUi(self, Newhard):
        Newhard.setObjectName("Newhard")
        Newhard.resize(400, 294)
        font = QtGui.QFont()
        font.setPointSize(12)
        Newhard.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Newhard)
        self.gridLayout.setObjectName("gridLayout")

        self.name_label = QtWidgets.QLabel(Newhard)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)

        self.name_line = QtWidgets.QLineEdit(Newhard)
        self.name_line.setObjectName("name_line")
        self.name_line.setClearButtonEnabled(True)
        self.gridLayout.addWidget(self.name_line, 1, 0, 1, 2)

        self.pll_label = QtWidgets.QLabel(Newhard)
        self.pll_label.setObjectName("pll_label")
        self.pll_line = QtWidgets.QSpinBox(Newhard)
        self.pll_line.setObjectName("pll_line")
        self.pll_label.hide()
        self.pll_line.hide()

        self.memory_label = QtWidgets.QLabel(Newhard)
        self.memory_label.setObjectName("memory_label")
        self.memory_line = QtWidgets.QSpinBox(Newhard)
        self.memory_line.setObjectName("memory_line")
        self.memory_label.hide()
        self.memory_line.hide()

        self.pin_label = QtWidgets.QLabel(Newhard)
        self.pin_label.setObjectName("pin_label")
        self.pin_line = QtWidgets.QSpinBox(Newhard)
        self.pin_line.setObjectName("pin_line")
        self.pin_label.hide()
        self.pin_line.hide()

        self.mult_label = QtWidgets.QLabel(Newhard)
        self.mult_label.setObjectName("mult_label")
        self.mult_line = QtWidgets.QSpinBox(Newhard)
        self.mult_line.setObjectName("mult_line")
        self.mult_label.hide()
        self.mult_line.hide()

        self.log_label = QtWidgets.QLabel(Newhard)
        self.log_label.setObjectName("log_label")
        self.log_line = QtWidgets.QSpinBox(Newhard)
        self.log_line.setObjectName("log_line")
        self.log_label.hide()
        self.log_line.hide()

        self.type_label = QtWidgets.QLabel(Newhard)
        self.type_label.setObjectName("type_label")
        self.gridLayout.addWidget(self.type_label, 2, 0, 1, 1)
        self.type_line = QtWidgets.QComboBox(Newhard)
        self.type_line.addItems(['other', 'PLD'])
        self.type_line.setObjectName("type_line")
        self.gridLayout.addWidget(self.type_line, 3, 0, 1, 2)
        self.description_label = QtWidgets.QLabel(Newhard)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 4, 0, 1, 1)
        self.description_line = QtWidgets.QLineEdit(Newhard)
        self.description_line.setClearButtonEnabled(True)
        self.description_line.setObjectName("description_line")
        self.gridLayout.addWidget(self.description_line, 5, 0, 1, 2)
        self.spec_radio = QtWidgets.QRadioButton(Newhard)
        self.spec_radio.setObjectName("spec_radio")
        self.gridLayout.addWidget(self.spec_radio, 6, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Newhard)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)

        self.retranslateUi(Newhard)
        self.buttonBox.accepted.connect(Newhard.accept) # type: ignore
        self.buttonBox.rejected.connect(Newhard.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Newhard)

    def retranslateUi(self, Newhard):
        _translate = QtCore.QCoreApplication.translate
        Newhard.setWindowTitle(_translate("Newhard", "Добавление новой платы"))
        self.name_label.setText(_translate("Newhard", "Название"))
        self.type_label.setText(_translate("Newhard", "Тип"))
        self.description_label.setText(_translate("Newhard", "Описание"))
        self.spec_radio.setText(_translate("Newhard", "Спецификация"))
        self.pll_label.setText(_translate("Newhard", "PLL"))
        self.memory_label.setText(_translate("Newhard", "Память"))
        self.log_label.setText(_translate("Newhard", "Логические элементы"))
        self.mult_label.setText(_translate("Newhard", "Multiplier"))
        self.pin_label.setText(_translate("Newhard", 'Количество пинов'))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Newhard = QtWidgets.QDialog()
    ui = Ui_Newhard()
    ui.setupUi(Newhard)
    Newhard.show()
    sys.exit(app.exec_())
