# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hardware.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Newhard(object):
    def setupUi(self, Newhard):
        Newhard.setObjectName("Newhard")
        Newhard.resize(400, 449)
        font = QtGui.QFont()
        font.setPointSize(12)
        Newhard.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Newhard)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(Newhard)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.type_label = QtWidgets.QLabel(self.splitter_2)
        self.type_label.setObjectName("type_label")
        self.type_line = QtWidgets.QLineEdit(self.splitter_2)
        self.type_line.setClearButtonEnabled(True)
        self.type_line.setObjectName("type_line")
        self.gridLayout.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(Newhard)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.spec_label = QtWidgets.QLabel(self.splitter_4)
        self.spec_label.setObjectName("spec_label")
        self.spec_line = QtWidgets.QLineEdit(self.splitter_4)
        self.spec_line.setClearButtonEnabled(True)
        self.spec_line.setObjectName("spec_line")
        self.gridLayout.addWidget(self.splitter_4, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Newhard)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.name_label = QtWidgets.QLabel(self.splitter)
        self.name_label.setObjectName("name_label")
        self.name_line = QtWidgets.QLineEdit(self.splitter)
        self.name_line.setClearButtonEnabled(True)
        self.name_line.setObjectName("name_line")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(Newhard)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.description_label = QtWidgets.QLabel(self.splitter_3)
        self.description_label.setObjectName("description_label")
        self.description_line = QtWidgets.QLineEdit(self.splitter_3)
        self.description_line.setClearButtonEnabled(True)
        self.description_line.setObjectName("description_line")
        self.gridLayout.addWidget(self.splitter_3, 2, 0, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(Newhard)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.count_label = QtWidgets.QLabel(self.splitter_5)
        self.count_label.setObjectName("count_label")
        self.count_line = QtWidgets.QLineEdit(self.splitter_5)
        self.count_line.setClearButtonEnabled(True)
        self.count_line.setObjectName("count_line")
        self.gridLayout.addWidget(self.splitter_5, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Newhard)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)

        self.retranslateUi(Newhard)
        self.buttonBox.accepted.connect(Newhard.accept) # type: ignore
        self.buttonBox.rejected.connect(Newhard.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Newhard)

    def retranslateUi(self, Newhard):
        _translate = QtCore.QCoreApplication.translate
        Newhard.setWindowTitle(_translate("Newhard", "Добавление новой платы"))
        self.type_label.setText(_translate("Newhard", "Тип"))
        self.spec_label.setText(_translate("Newhard", "Спецификация"))
        self.name_label.setText(_translate("Newhard", "Название"))
        self.description_label.setText(_translate("Newhard", "Описание"))
        self.count_label.setText(_translate("Newhard", "Количество"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Newhard = QtWidgets.QDialog()
    ui = Ui_Newhard()
    ui.setupUi(Newhard)
    Newhard.show()
    sys.exit(app.exec_())
